[package]
name = "nnsdk"
version = "0.1.0"
authors = ["jam1garner <jam1.mcleod@hotmail.com>"]
edition = "2018"
license = "MIT"
description = "Cleanroom reverse-engineered bindings for nnsdk (Nintendo Switch SDK)"
documentation = "https://docs.rs/nnsdk"

[dependencies]
libc-nnsdk = { git = "https://github.com/inspier/libc-nnsdk", features = ["rustc-dep-of-std"] }
rustc-std-workspace-core = { version = "1", optional = true }

[features]
rustc-dep-of-std = ["rustc-std-workspace-core"]
